### ISSUE TITLE
More Bugs

### ISSUE THREAD

**Issue by TheHunter1234** [LuckFire/amoled-cord#22]
After the update it broke my custom CSS, how would this be fixed.

```
/*embed redesign*/
:root{
    --embed-border-radius: 8px;
}
.embed-IeVjo6 {
    border-radius: var(--embed-border-radius);
}
.embed-IeVjo6 code{
    background: var(--background-secondary);
}
:root{
    --embed-line-width: 256px;
}
.embedWrapper-lXpS3L{
}
.embedFull-2tM8-- {

    border-left: calc(4px + var(--embed-line-width)) solid var(--background-accent);
    background: var(--background-secondary);
}
.grid-1nZz7S {
    margin-left: calc( -1 * var(--embed-line-width));
    z-index: 1;
}
.embedFull-2tM8--:after, .embedFull-2tM8--:before{
    content: "";
    height: 100%;
    width: var(--embed-line-width);
    position: absolute;
    top: 0;
    left: calc(-1 * var(--embed-line-width));
}
.embedFull-2tM8--:after{
    background: linear-gradient(to right, transparent, var(--background-secondary));
}
.embedFull-2tM8--:before{
    background: var(--background-secondary);
    opacity: .8;
}
```
causes this to happen
![image](https://user-images.githubusercontent.com/69104450/144693711-fe4f08e6-e402-49eb-896f-69f2e7c56ead.png)

**Comment by LuckFire** [comment]
```css
/*embed redesign*/
:root{
    --embed-border-radius: 8px;
}
.embed-IeVjo6 {
    border-radius: var(--embed-border-radius);
}
.embed-IeVjo6 code{
    background: var(--background-light);
}
:root{
    --embed-line-width: 256px;
}
.embedWrapper-lXpS3L{
}
.embedFull-2tM8-- {
    border-left: calc(4px + var(--embed-line-width)) solid var(--background-accent);
    background: var(--background-light);
}
.grid-1nZz7S {
    margin-left: calc( -1 * var(--embed-line-width));
    z-index: 1;
}
.embedFull-2tM8--:after, .embedFull-2tM8--:before{
    content: "";
    height: 100%;
    width: var(--embed-line-width);
    position: absolute;
    top: 0;
    left: calc(-1 * var(--embed-line-width));
}
.embedFull-2tM8--:after{
    background: linear-gradient(to right, transparent, var(--background-light));
}
.embedFull-2tM8--:before{
    background: var(--background-light);
    opacity: .8;
}
```
