### ISSUE TITLE
[IMPROPERLY THEMED]: Scroller/Scrollbar Color Indistinguishable

### ISSUE THREAD

**Issue by amxmu** [LuckFire/amoled-cord#88]
### Client Mod

Vencord

### Please provide screenshots of the unthemed areas.

If if it possible to change, could the scroller/scrollbar be made lighter? It's kind of impossible (at least for me) to distinguish it from the right sidebar

![amoledcord scrollbar color](https://github.com/LuckFire/amoled-cord/assets/92172841/811feca9-bdbb-4daf-b4e5-d1cf309e887a)

### Before Submitting

- [X] I checked for similar reports of this issue.
- [X] I am on the latest stable Discord version.
- [X] I am on the latest version of the theme.
- [X] I have reinstalled the theme.

**Comment by LuckFire** [comment]
Making it any lighter would make it too noticeable, so I have no plans to change the brightness of it.

If you want to modify them yourself, you can mess with these variables.
```css
:root {
    --scrollbar-auto-scrollbar-color-track: var(--primary-860) !important;
    --scrollbar-auto-scrollbar-color-thumb: var(--primary-800) !important;
    --scrollbar-auto-thumb: var(--primary-800) !important;
    --scrollbar-auto-track: var(--primary-860) !important;
    --scrollbar-thin-thumb: var(--primary-800) !important;
}
```
